C----------------------------------------------------------------
C     SAMUEL GERAGHTY TCD GERAGHS7@TCD.IE
C     03/2021 UMAT LEARNING EXCERCISES
C     UMAT FOR ISOTROPIC ELASTICITY
C     INCORPORATES 3D, AXISYMMETRIC AND PLANE STRESS FORMULATIONS
C     ISOTROPIC ELASTICITY FORUMATION DERIVED FROM GOULD, P., 
C     INTRODUCTION TO LINEAR ELASTICITY, CHAPTER 4
C     PLANE STRAIN AND STRESS DERIVED FROM EN2340 COMPUTATIONAL METHODS
C     IN SOLID MECHANICS, ALLAN BOWER, BROWN UNIVERITY
C     INCLUDES FOLLOWING FORMULATIONS OF 3D ISOTROPIC ELASTICITY
C 	  	-AXISYMMETRIC STRESS
C 		-PLANE STRESS
C 		-GENERAL 3D STRESS
C----------------------------------------------------------------
C     SUBROUTINE DEFINED VARIABLES IN ORDER OF DECLARATION
C    	STRESS(NTENS) - STRESS TENSOR AT BEGINNING OF INCREMENT
C     	STATEV(NSTATV) - ARRAY OF SOLUTION DEPENDENT VARIABLES
C     	DDSDDE - JACOBIAN MATRIX OF CONSITUTIVE MODEL
C     	SSE - SPECIFIC ELASTIC STRAIN ENERGY
C     	SPD - SPECIFICPLASTIC DISSIPATION
C     	SCD - SPECIFIC CREEP DISSIPATION
C     	RPL - VOLUMETRIC HEAT GENERATION PER UNIT TIME FROM WORK
C     	DDSDDT - VARIATION OF STRESS INCREMENTS WRT TO TEMPERATURE
C     	DRPLDE - VARIATION OF RPL WRT STRAIN INCREMENTS
C     	DRPLDT - VARIATION OF RPL WRT TEMPERATURE
C    	STRAN(NTENS) - ARRAY OF TOTAL STRAINS AT INCREMENT BEGINNING
C       DSTRAN(NTENS) - ARRAY OF STRAIN INCREMENTS
C	TIME - TIME RELATED ARRAY
C 		TIME (1): VALUE OF TIME STEP AT BEGINNING OF INCREMENT
C 		TIME (2): VALUE OF TOTAL TIME AT BEGINNING OF INCREMENT
C	DTIME - TIME INCREMENT
C 	TEMP - TEMPERATURE AT START OF INCREMENT
C 	DTEMP - INCREMENT OF TEMPERATURE
C 	PREDEF - ARRAY OF INTERP. VALUES OF PREDEFINED FIELD VARIALBES
C 	DPRED - ARRAY OF INCREMENTS OF PREDEFINED FIELD VARIABLES
C 	CMNAME - UMAT NAME
C       NDI - NUMBER OF DIRECT STRESS COMPONENTS AT THIS POINT
C 	NSHR - NUMBER OF ENG. STRAIN COMPONENTS AT THIS POINT
C     	NTENS - SIZE OF STRESS OR STRAIN COMPONENT ARRAY (NDI + NSHR)
C     	NSTATV - NUMBER OF SOLUTION DEPENDENT STATE VARIABLES
C     	PROPS - USER SPECIFIED ARRAY OF MATERIAL CONSTANTS
C 	NPROPS - USER DEFINED NUMBER OF MATERIAL CONSTANTS
C 	COORDS - ARRAY OF COORDINATES OF THIS POINT
C 	DROT - ROTATION INCREMENT MATRIX RIGID BODY ROTATION
C 	PNEWDT - RATIO OF SUGGESTED NEW TIME INCREMENT TO CURRENT ONE
C 	CELENT - CHARACTERISTIC ELEMENT LENGTH
C 	DFGRD0 - DEFORMATION GRADIENT AT BEGINNING OF INCREMENT
C 	DFGRD1 - DEFORMATION GRADIENT AT END OF INCREMENT
C 	NOEL - ELEMENT NUMBER
C 	NPT - INTEGRATION POINT NUMBER
C 	LAYER - LATER NUMBER FOR COMPOSITE SHELLS AND LAYERED SOLIDS
C 	KSPT - SECTION POINT NUMBER WITHIN CURRENT LAYER
C 	KSTEP - ARRAY FOR STEP INFORMATION
C 		KSTEP (1): STEP NUMBER
C 		KSTEP (2): PROCEDURE KEY TYPE
C 		KSTEP (3): 1 FOR NLGEOM FOR CURRENT STEP, 0 OTHERWISE
C 		KSTEP (4): 1 IF CURRENT STEP IS LINEAR PERTUBATION PROCEDURE, 0 OTHERWISE
C 	KINC - INCREMENT NUMBER
C----------------------------------------------------------------
C
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,STRAN,DSTRAN,
     2 TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,
     3 NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,
     4 DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C
C----------------------------------------------------------------
C
C     NOTE THAT ALL VARIABLES MUST HAVE FIRST LETTERS BETWEEN A-H, O-Z
C     FOR DOUBLE PRECISION, ALL OTHERS ARE INTEGERS BY DEFAULT
      INCLUDE 'ABA_PARAM.INC'
C
C----------------------------------------------------------------
C
C     DEFINING DIMENSIONS OF MATERIAL NAME AND PARAMETERS
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),
     4 DFGRD0(3,3),DFGRD1(3,3), KSTEP(4)
C
C----------------------------------------------------------------
C
C     DEFINE DIMENSION OF LOCAL ARRAYS AND PARAMETERS
      DIMENSION EELAS(6),EPLAS(6),FLOW(6)
      PARAMETER ZERO=0.D0,ONE=1.0D0,TWO=2.0D0,THREE=3.0D0,SIX=6.0D0
	  PARAMETER ENUMAX=0.499D0, NEWTON=10, TOLER=1.0D-6
C
C----------------------------------------------------------------
C     VARIABLES USED IN CODE FOR ANALYSIS AND DESCRIPTION
C     	PROPS(1) - EMOD  - YOUNG'S MODULUS
C     	PROPS(2) - ENU - POISSON'S RATIO
C 	ELAMBDA - LAMES FIRST PARAMATER
C 	EMU - SHEAR MODULUS OR LAMES SECOND PARAMETER
C       EKAPPA - PLANE STRESS PARAMETER
C----------------------------------------------------------------
C	  ELASTIC PROPERTIES
	  EMOD = PROPS(1)
	  ENU = PROPS(2)
	  EMU = EMOD/(TWO*(ONE+ENU))
	  ELAMBDA = (ENU*EMOD)/((ONE+ENU)*(ONE-TWO*ENU))
	  EKAPPA = EMOD/(ONE-ENU*ENU)
C----------------------------------------------------------------	  
C     ELASTIC STIFFNESS MATRIX FORMULATION
C     AXISYMMETRIC & PLANE STRAIN STIFFNES MATRIX
      IF (NDI==3 .AND. NSHR==1) THEN
		WRITE(6,*)"PSTRAIN"
		DO K1 = 1,NDI
			DO K2 = 1,NDI
				DDSDDE(K2,K1) = ELAMBDA
			END DO
			DDSDDE(K1,K1) = ONE - ELAMBDA
		END DO
		DO K1 = NDI+1,NTENS
			DDSDDE(K1,K1) = EMU
		END DO
C 	  PLANE STRESS STIFFNES MATRIX
	  ELSE IF (NDI==2 .AND. NSHR==1) THEN
		WRITE(6,*)"PSTRESS"
		DO K1 = 1,NDI
			DO K2 = 1,NDI
				DDSDDE(K2,K1) = EKAPPA*ENU
			END DO
			DDSDDE(K1,K1) = EKAPPA
		END DO
		DO K1 = NDI+1,NTENS
			DDSDDE(K1,K1) = 0.5D0*EKAPPA*(ONE-ENU)
		END DO
C     3D STIFFNESS MATRIX
	  ELSE
		WRITE(6,*)"3D"
		DO K1 = 1,NDI
			DO K2 = 1,NDI
				DDSDDE(K2,K1) = ELAMBDA
			END DO
			DDSDDE(K1,K1) = TWO*EMU+ELAMBDA
		END DO
		DO K1 = NDI+1,NTENS
			DDSDDE(K1,K1) = TWO*EMU
		END DO
	  END IF 
C----------------------------------------------------------------
C 	  STRESS CALCULATION
	  DO K1 = 1,NTENS
		DO K2 = 1,NTENS
			STRESS(K2) = STRESS(K2)+DDSDDE(K2,K1)*DSTRAN(K1)
			END DO
		END DO
C----------------------------------------------------------------
	  RETURN
	  END 
	
